[package]
name = "tailcall-prettier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = { workspace = true }
lazy_static = "1.4.0"
strum_macros = "0.26.2"
tokio.workspace = true
